[versions]
agp = "8.12.0"
aboutLibraries = "13.2.1"
adaptive = "1.3.0-alpha02"
advancedMenubar = "0.1.0-alpha03"
androidx-activity = "1.12.3"
androidx-lifecycle = "2.10.0-alpha06"
androidx-crypto = "1.1.0"
androidx-biometric = "1.4.0-alpha02"
animateCompose = "0.0.1"
buildconfig = "6.0.7"
capturable = "2.0.1"
confettikit = "0.7.0"
coreSplashscreen = "1.2.0"
#noinspection NewerVersionAvailable
credential-storage = "1.0.0"
composeMultiplatform = "1.10.1"
emoji = "2.3.0"
haze = "1.7.0"
koalaplotCore = "0.9.1"
kotlin = "2.3.10"
ktlint = "14.0.1"
alarmee = "2.3.1"
kotlinxDatetime = "0.7.1"
kotlinx-coroutines = "1.10.2"
kotlinxSerializationJson = "1.10.0"
ktorClientCore = "3.4.0"
jbrApi = "1.10.1"
jetlime = "4.1.1"
material3 = "1.10.0-alpha05"
materialIconsExtended = "1.7.3"
materialyou = "0.3.0"
multihapticCompose = "0.3.0"
nucleus = "1.0.2"
permission = "0.13.0"
platformtools = "0.7.5"
proguard = "7.8.2"
navigationCompose = "2.9.1"
materialKolor = "4.1.1"
multiplatformSettings = "1.3.0"
#noinspection NewerVersionAvailable
oidc = "0.15.3"
smartspacer-sdk = "1.1"
sonner = "0.3.9"

# App configurations
appName = "Beste-Noten-App"
appVersion = "1.2.0"
appVersionCode = "6"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"
macos-minSdk = "15.0"
macos-targetSdk = "26.0"

[libraries]
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
advanced-menubar = { module = "dev.hansholz:advanced-menubar", version.ref = "advancedMenubar" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
animate-compose = { module = "com.nomanr:animate-compose", version.ref = "animateCompose" }
capturable = { module = "io.github.jmseb3:capturable", version.ref = "capturable" }
capturable-extension = { module = "io.github.jmseb3:capturableExtension", version.ref = "capturable" }
components-resources = { module = "org.jetbrains.compose.components:components-resources", version.ref = "composeMultiplatform" }
confettikit = { module = "io.github.vinceglb:confettikit", version.ref = "confettikit" }
credential-secure-storage = { module = "com.microsoft:credential-secure-storage", version.ref = "credential-storage" }
emoji-compose-m3 = { module = "org.kodein.emoji:emoji-compose-m3", version.ref = "emoji" }
foundation = { module = "org.jetbrains.compose.foundation:foundation", version.ref = "composeMultiplatform" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplotCore" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
alarmee = { module = "io.github.tweener:alarmee", version.ref = "alarmee" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-security-crypto = { module = "androidx.security:security-crypto-ktx", version.ref = "androidx-crypto" }
androidx-biometric = { module = "androidx.biometric:biometric-ktx", version.ref = "androidx-biometric" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-apache5 = { module = "io.ktor:ktor-client-apache5", version.ref = "ktorClientCore" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientCore" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientCore" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClientCore" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktorClientCore" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientCore" }
material-icons-extended = { module = "org.jetbrains.compose.material:material-icons-extended", version.ref = "materialIconsExtended" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
material3 = { module = "org.jetbrains.compose.material3:material3", version.ref = "material3" }
materialyou = { module = "dev.zwander:materialyou", version.ref = "materialyou" }
multihaptic-compose = { module = "top.ltfan.multihaptic:multihaptic-compose", version.ref = "multihapticCompose" }
nucleus-core-runtime = { module = "io.github.kdroidfilter:nucleus.core-runtime", version.ref = "nucleus" }
oidc-appsupport = { module = "io.github.kalinjul.kotlin.multiplatform:oidc-appsupport", version.ref = "oidc" }
permission = { module = "tech.kotlinlang:permission", version.ref = "permission" }
platformtools-darkmodedetector = { module = "io.github.kdroidfilter:platformtools.darkmodedetector", version.ref = "platformtools" }
jbr-api = { module = "org.jetbrains.runtime:jbr-api", version.ref = "jbrApi" }
jetlime = { module = "io.github.pushpalroy:jetlime", version.ref = "jetlime" }
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "adaptive" }
material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "adaptive" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
runtime = { module = "org.jetbrains.compose.runtime:runtime", version.ref = "composeMultiplatform" }
ui = { module = "org.jetbrains.compose.ui:ui", version.ref = "composeMultiplatform" }
ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "composeMultiplatform" }
smartspacer-sdk = { module = "com.kieronquinn.smartspacer:sdk-plugin", version.ref = "smartspacer-sdk" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }

[plugins]
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
nucleus = { id = "io.github.kdroidfilter.nucleus", version.ref = "nucleus" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }