[versions]
agp = "8.10.1"
adaptive = "1.2.0-alpha03"
androidx-activity = "1.10.1"
androidx-lifecycle = "2.9.1"
androidx-crypto = "1.1.0-beta01"
androidx-biometric = "1.4.0-alpha02"
animateCompose = "0.0.1"
buildconfig = "5.6.7"
confettikit = "0.5.1"
credential-storage = "1.0.0"
composeHotReload = "1.0.0-beta03"
composeMultiplatform = "1.9.0-alpha03"
emoji = "2.2.0"
haze = "1.6.7"
koalaplotCore = "0.9.0"
kotlin = "2.2.0"
kotlinxDatetime = "0.7.1-0.6.x-compat"
kotlinx-coroutines = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ktorClientCore = "3.2.1"
jbrApi = "1.5.1"
jna = "5.17.0"
platformtools = "0.4.0"
navigationCompose = "2.9.0-beta03"
materialKolor = "3.0.0-beta07"
multiplatformSettings = "1.3.0"
oidc = "0.15.0"
sonner = "0.3.8"

# App configurations
appName = "Beste-Noten-App"
appVersion = "1.0.0"
appVersionCode = "1"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

[libraries]
adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
animate-compose = { module = "com.nomanr:animate-compose", version.ref = "animateCompose" }
confettikit = { module = "io.github.vinceglb:confettikit", version.ref = "confettikit" }
credential-secure-storage = { module = "com.microsoft:credential-secure-storage", version.ref = "credential-storage" }
emoji-compose-m3 = { module = "org.kodein.emoji:emoji-compose-m3", version.ref = "emoji" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplotCore" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
androidx-lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-security-crypto = { module = "androidx.security:security-crypto-ktx", version.ref = "androidx-crypto" }
androidx-biometric = { module = "androidx.biometric:biometric-ktx", version.ref = "androidx-biometric" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktorClientCore" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientCore" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClientCore" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktorClientCore" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientCore" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
oidc-appsupport = { module = "io.github.kalinjul.kotlin.multiplatform:oidc-appsupport", version.ref = "oidc" }
platformtools-darkmodedetector = { module = "io.github.kdroidfilter:platformtools.darkmodedetector", version.ref = "platformtools" }
jbr-api = { module = "org.jetbrains.runtime:jbr-api", version.ref = "jbrApi" }
jna-core = { module = "net.java.dev.jna:jna", version.ref = "jna" }
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "adaptive" }
material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "adaptive" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "composeMultiplatform" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }