[versions]
agp = "8.11.2"
aboutLibraries = "12.2.4"
adaptive = "1.2.0-alpha06"
advancedMenubar = "0.1.0-alpha02"
androidx-activity = "1.11.0"
androidx-lifecycle = "2.10.0-alpha01"
androidx-crypto = "1.1.0"
androidx-biometric = "1.4.0-alpha02"
animateCompose = "0.0.1"
buildconfig = "5.6.8"
confettikit = "0.6.0"
#noinspection NewerVersionAvailable
credential-storage = "1.0.0"
composeHotReload = "1.0.0-beta08"
composeMultiplatform = "1.10.0-alpha01"
emoji = "2.3.0"
haze = "1.7.0"
koalaplotCore = "0.9.1"
kotlin = "2.2.21"
ktlint = "13.1.0"
alarmee = "2.3.1"
kotlinxDatetime = "0.7.1"
kotlinx-coroutines = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ktorClientCore = "3.3.0"
jbrApi = "1.7.0"
jetlime = "4.0.0"
jna = "5.17.0"
materialyou = "0.2.9"
permission = "0.13.0"
platformtools = "0.6.1"
navigationCompose = "2.9.0-rc02"
#noinspection NewerVersionAvailable
materialKolor = "3.0.0-beta07"
multiplatformSettings = "1.3.0"
oidc = "0.15.1"
smartspacer-sdk = "1.1"
sonner = "0.3.8"

# App configurations
appName = "Beste-Noten-App"
appVersion = "1.0.2"
appVersionCode = "3"
android-compileSdk = "36"
android-minSdk = "24"
android-targetSdk = "36"

[libraries]
aboutlibraries-core = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-core = { module = "com.mikepenz:aboutlibraries-compose-core", version.ref = "aboutLibraries" }
aboutlibraries-compose-m3 = { module = "com.mikepenz:aboutlibraries-compose-m3", version.ref = "aboutLibraries" }
adaptive = { module = "org.jetbrains.compose.material3.adaptive:adaptive", version.ref = "adaptive" }
advanced-menubar = { module = "dev.hansholz:advanced-menubar", version.ref = "advancedMenubar" }
animate-compose = { module = "com.nomanr:animate-compose", version.ref = "animateCompose" }
confettikit = { module = "io.github.vinceglb:confettikit", version.ref = "confettikit" }
credential-secure-storage = { module = "com.microsoft:credential-secure-storage", version.ref = "credential-storage" }
emoji-compose-m3 = { module = "org.kodein.emoji:emoji-compose-m3", version.ref = "emoji" }
haze = { module = "dev.chrisbanes.haze:haze", version.ref = "haze" }
koalaplot-core = { module = "io.github.koalaplot:koalaplot-core", version.ref = "koalaplotCore" }
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
alarmee = { module = "io.github.tweener:alarmee", version.ref = "alarmee" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activity" }
lifecycle-runtime-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
lifecycle-viewmodel-compose = { module = "org.jetbrains.androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidx-lifecycle" }
androidx-security-crypto = { module = "androidx.security:security-crypto-ktx", version.ref = "androidx-crypto" }
androidx-biometric = { module = "androidx.biometric:biometric-ktx", version.ref = "androidx-biometric" }
kotlinx-coroutinesSwing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinxDatetime" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-apache5 = { module = "io.ktor:ktor-client-apache5", version.ref = "ktorClientCore" }
ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktorClientCore" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktorClientCore" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktorClientCore" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktorClientCore" }
ktor-client-js = { module = "io.ktor:ktor-client-js", version.ref = "ktorClientCore" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktorClientCore" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
materialyou = { module = "dev.zwander:materialyou", version.ref = "materialyou" }
oidc-appsupport = { module = "io.github.kalinjul.kotlin.multiplatform:oidc-appsupport", version.ref = "oidc" }
permission = { module = "tech.kotlinlang:permission", version.ref = "permission" }
platformtools-darkmodedetector = { module = "io.github.kdroidfilter:platformtools.darkmodedetector", version.ref = "platformtools" }
jbr-api = { module = "org.jetbrains.runtime:jbr-api", version.ref = "jbrApi" }
jetlime = { module = "io.github.pushpalroy:jetlime", version.ref = "jetlime" }
jna-core = { module = "net.java.dev.jna:jna", version.ref = "jna" }
material3-adaptive-layout = { module = "org.jetbrains.compose.material3.adaptive:adaptive-layout", version.ref = "adaptive" }
material3-adaptive-navigation = { module = "org.jetbrains.compose.material3.adaptive:adaptive-navigation", version.ref = "adaptive" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform-settings-no-arg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }
navigation-compose = { module = "org.jetbrains.androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
ui-backhandler = { module = "org.jetbrains.compose.ui:ui-backhandler", version.ref = "composeMultiplatform" }
smartspacer-sdk = { module = "com.kieronquinn.smartspacer:sdk-plugin", version.ref = "smartspacer-sdk" }
sonner = { module = "io.github.dokar3:sonner", version.ref = "sonner" }

[plugins]
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutLibraries" }
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
buildConfig = { id = "com.github.gmazzo.buildconfig", version.ref = "buildconfig" }
composeHotReload = { id = "org.jetbrains.compose.hot-reload", version.ref = "composeHotReload" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "composeMultiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }